### ISSUE TITLE
[RFE] Define Default Registry in Chart Values

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#11]
Request Description:
The current Rancher-Cluster-Templates chart lacks the capability for users to define a default registry within the chartValues section.

Example:
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: ds01
  namespace: fleet-default
spec:
  rkeConfig:
    chartValues:
      global:
        rke2.registry.default: private.registry.com
```

**Comment by bcdurden** [comment]
This feature already exists:

Values:
```yaml
systemDefaultRegistry:  registry.myurl.com
```

[Template](https://github.com/rancherfederal/rancher-cluster-templates/blob/c36e9fbf228f06fa8c07b7e4fbc1c7a8799f0587/charts/cluster-templates/templates/cluster.yaml#L216C60-L216C81): 
```yaml
system-default-registry: {{ .Values.cluster.config.systemDefaultRegistry }}
```

Result:
```yaml
machineSelectorConfig:
- config:
  system-default-registry: registry.myurl.com
```

**Comment by bcdurden** [comment]
Will add mention in vsphere values

**Comment by zlmitchell** [comment]
@bcdurden 
You will need to confirm what is the correct YAML line to add this. As what you are suggesting does not work, or is it how the vSphere Provisioner in Rancher creates the output YAML which does work. When using Rancher to Provision and using the UI to configure the default registry it gets put in here

```
spec:
  rkeConfig:
    chartValues:
      global:
        rke2.registry.default: private.registry.com
```
NOT where you have defined it in you previous comments. So I can only assume that the configuration is invalid. Rancher MCM Cluster provisioning has the correct configuration and has been that way for years.
