### ISSUE TITLE
[RFE] Make OS Configurable

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#15]
#Feature Request

Request description:
OS isn't configurable (not sure if the default is linux not what windows is not supported)

Example:
```
apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: nc-vsphere-master-config
  namespace: fleet-default
network:
- /Example/VM-Network
os: linux
cfgparam:
- disk.enableUUID=TRUE
```
