### ISSUE TITLE
Nodepool ﻿﻿machineDeploymentAnnotations doesn't handle multiple annonotions

### ISSUE THREAD

**Issue by andrew-morris-rgs** [rancherfederal/rancher-cluster-templates#32]
I am trying to set machineDeploymentAnnoations for cluster autoscaling, with a values file something like this
```
nodepools:
  - name: somecluster
     machineDeploymentAnnotations:
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
        cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
      ...
```

It fails with JSON parsing errors though. If I put just one line in the annoations it will pass that to the cluster config just fine.
