### ISSUE TITLE
inconsistency on TLS-SAN parameter between Template end Value File example

### ISSUE THREAD

**Issue by seb-835** [rancherfederal/rancher-cluster-templates#50]
Hi Team,

there is an inconsistency on TLS-SAN parameter,   "_" vs "-"
template file use :  **.cluster.config.globalConfig.tls_san** while value file  : **.cluster.config.globalConfig.tls-san**

in cluster.yaml template  line 91-93,  we have: 
```
      {{- if .Values.cluster.config.globalConfig.tls_san }}
      tls-san: {{ .Values.cluster.config.globalConfig.tls_san  | toRawJson }}
      {{- end }}
```
expecting values to be: added  throught tls_san  parameter.

But the values-xxx.yml files examples show a tls-san parameter.
```
    globalConfig:
      systemDefaultRegistry: docker.io # default registry
      cni: canal # canal, calico, cilium, multus,canal, multus,calico, multus,cilium
      docker: false
      # token: ''
      # tls-san:
        # - url
        # - ip
``` 

Which one to fix ?   template or value ?
