### ISSUE TITLE
[RFE] - Provide the ability to disable features like rke2-ingress-nginx

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#6]
#Feature Request

Request description:
Customer is currently unable to disable certain features, such as rke2-ingress-nginx, via the Rancher-Cluster-Templates chart.

Additional notes:
Provide configuration options in the cluster.yaml to allow disabling of specific features, for instance, rke2-ingress-nginx.

Example:

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: ds01
  namespace: fleet-default
spec:
  defaultPodSecurityAdmissionConfigurationTemplateName: rancher-privileged
  rkeConfig:
    machineGlobalConfig:
      disable:
      - rke2-ingress-nginx

```

**Comment by bcdurden** [comment]
Verified that the `disable` field is present in the `machineGlobalConfig` map.

Example:
```yaml
    machineGlobalConfig:
      disable:
        - rke2-ingress-nginx
```

This would need to be added to helm chart to enable.
