### ISSUE TITLE
[RFE] Support for Configuring tls-sans in Rancher Cluster Templates

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#7]
#Feature Request

Request description:
Currently, the Rancher Cluster Templates do not offer a clear way to configure tls-sans through the cluster.yaml file.

Additional notes:
Implement a feature within the Rancher Cluster Templates chart that allows users to easily set tls-sans through the cluster.yaml configuration file.

Example:
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: example-cluster
  namespace: fleet-default
spec:
  rkeConfig:
    tls-san:
      - example.com
```
