### ISSUE TITLE
[RFE] Allow Setting defaultPodSecurityAdmissionConfigurationTemplateName in Cluster Templates

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#8]
#Feature Request

Request description:
The current version of the Rancher Cluster Templates does not provide an option to set defaultPodSecurityAdmissionConfigurationTemplateName in the cluster.yaml configuration. 

Example:
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: sample-cluster
  namespace: fleet-default
spec:
  defaultPodSecurityAdmissionConfigurationTemplateName: rancher-privileged

```
