### ISSUE TITLE
[RFE] Correct Configuration of kubelet-arg in Rancher Cluster Templates

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#9]
#Feature Request

Request description:
The customer has reported that within the Rancher Cluster Templates, the placement of kubelet-arg configurations in the cluster.yaml file seems to be either incorrect or not optimal. 

Additional notes:
Customer propose an enhancement to the Rancher Cluster Templates that ensures kubelet-arg can be set accurately and effectively, reflecting in the appropriate section of the cluster.yaml. 

Example:
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: ds01
  namespace: fleet-default
spec:
  defaultPodSecurityAdmissionConfigurationTemplateName: rancher-privileged
  rkeConfig:
    machineGlobalConfig:
      disable:
      - rke2-ingress-nginx 
    tls-san:
      - <domain name here>
    machineSelectorConfig:
    - config:
        kubelet-arg: 
         - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
         - authorization-mode=Webhook
         - streaming-connection-idle-timeout=5m
```
